version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: csi_database
    environment:
      MYSQL_ROOT_PASSWORD: root_password  
      MYSQL_DATABASE: csidata             
      MYSQL_USER: user                    
      MYSQL_PASSWORD: user_password       
    ports:
      - "3306:3306"
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d  
    networks:
      - csi_network

networks:
  csi_network:
    driver: bridge
